# SPDX-License-Identifier: MPL-2.0

from __future__ import annotations

from typing import Protocol


class ClientAdapter(Protocol):
    def open_session_events(self, native_obj) -> list[dict]: ...
    def close_session_events(self, native_obj) -> list[dict]: ...
    def map_turn(self, native_turn) -> dict: ...
    def map_state_update(self, native_state) -> dict: ...
